spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:9000/bootTasks?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8083

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
