spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:9000/bootUser?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
server:
  port: 8082
#Eureka
eureka:
  client:
    service-url:
      default-zone: http://sahil:sahil@localhost:8761/eureka/
logging:
  file:
    name: user-service.log